import { DEPLOYMENT_STATUS, IDeployment } from "@/utils/types";
const { Timestamp } = require("firebase-admin/firestore")

export const mockdeployments: IDeployment[] = [
  {
    id: "b119nHZJEAIWKiIWC90g",
    status: DEPLOYMENT_STATUS.FAILURE,
    module: "data_science",
    variables: {
      billing_budget_alert_spent_percents: [Array],
      create_budget: true,
      enable_services: true,
      enable_gpu_driver: "",
      billing_budget_pubsub_topic: false,
      region: "us-west1",
      billing_budget_credit_types_treatment: "INCLUDE_ALL_CREDITS",
      container_image_tag: "latest",
      container_image_repository: "",
      create_network: true,
      billing_budget_amount: 500,
      notebook_count: 1,
      folder_id: "411211453280",
      organization_id: "348671237177",
      create_usermanaged_notebook: true,
      billing_budget_notification_email_addresses: [],
      boot_disk_size_gb: 100,
      network_name: "ai-notebook",
      zone: "us-west1-a",
      boot_disk_type: "PD_SSD",
      set_vpc_peering_policy: false,
      image_project: "deeplearning-platform-release",
      gpu_accelerator_core_count: "",
      set_shielded_vm_policy: false,
      create_project: true,
      billing_budget_alert_spend_basis: "CURRENT_SPEND",
      machine_type: "n1-standard-1",
      create_container_image: "",
      ip_cidr_range: "10.142.190.0/24",
      gpu_accelerator_type: "",
      trusted_groups: [],
      billing_budget_amount_currency_code: "USD",
      project_id_prefix: "radlab-prefix-id",
      resource_creator_identity: "",
      billing_budget_labels: {},
      image_family: "tf-latest-cpu",
      set_domain_restricted_sharing_policy: false,
      billing_account_id: "0195C4-1D8258-85DB33",
      trusted_users: [],
      billing_budget_services: [],
      subnet_name: "subnet-ai-notebook",
    },
    deploymentId: "3701",
    deployedByEmail: "developer@example.com",
    builds: [],
    createdAt: Timestamp.now(),
    projectId: "radlab-data-science-3701",
  },
]

