// Limit these to limit CSS size
module.exports = [
  "light",
  "dark",
  // "synthwave",
  // "dracula",
  // "fantasy",
  // "autumn",
  // "cupcake",
  // "bumblebee",
  // "emerald",
  // "corporate",
  // "retro",
  // "cyberpunk",
  // "valentine",
  // "halloween",
  // "garden",
  // "forest",
  // "aqua",
  // "lofi",
  // "pastel",
  // "wireframe",
  // "black",
  // "luxury",
  // "cmyk",
  // "business",
  // "acid",
  // "lemonade"
]
