# .github/workflows/check-tf-plan.yml

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'CHECK - Terraform Plan'

on:
  # pull_request:
  #   types: [opened, reopened]
  #   paths:
  #     - 'modules/**/*.tf'
  workflow_dispatch:
    inputs:
      PRNumber:
        description: 'PR #'     
        required: true
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.0.11

      - name: Set environment
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=${GITHUB_WORKSPACE}/.github/workflows/fake-key.json" >> $GITHUB_ENV
          echo $GOOGLE_APPLICATION_CREDENTIALS # This will print the file path in GOOGLE_APPLICATION_CREDENTIALS variable
          # cat $GOOGLE_APPLICATION_CREDENTIALS # This will print the file content

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: tools

      - name: execute py script (auto) # run the check-tf-plan.py
        id: tf-plan-auto
        if: github.event_name == 'pull_request'
        run: |
          python check-tf-plan.py ${{ github.event.number }}
        working-directory: tools

      - name: execute py script (manual) # run the check-tf-plan.py
        id: tf-plan-manual
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ github.event.inputs.PRNumber }}" =~ ^[0-9]+$ ]]
          then
            python check-tf-plan.py ${{ github.event.inputs.PRNumber }}
          else
            echo "INVALID PR Number ENTERED..."
            exit 1
          fi
        working-directory: tools
